/// Flutter icons LofiScifiClock
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LofiScifiClockIcons
///      fonts:
///       - asset: fonts/LofiScifiClockIcons.ttf
///
///
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
///
import 'package:flutter/widgets.dart';

class LofiScifiClockIcons {
  LofiScifiClockIcons._();

  static const _kFontFam = 'LofiScifiClockIcons';

  static const IconData sun = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData cloud_sun = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData wind = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData mist = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData rain = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData snowflake = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData clouds_flash_alt = const IconData(0xe807, fontFamily: _kFontFam);
}
